### ISSUE TITLE
Matterhorn releases (open-source project) is coupled strongly to matterhorn-pipeline

### ISSUE THREAD

**Issue by johnbeech** [bbc/matterhorn#20]
Every time infrastructure changes are made in matterhorn-pipeline, an update is required to Matterhorn in order to release these changes. Ideally, Matterhorn should have no knowledge of infrastructure or the pipeline project.

This can be solved by inverting the dependency; matterhorn-pipeline can hold its own version number schemas, and any/all files required in addition to the matterhorn service in order to resolve hosting in a given environment.

**Comment by AlexChesters** [comment]
it's been 4 years I'm assuming there's no strong desire to do this, closing it until such time

**Comment by johnbeech** [comment]
> it's been 4 years I'm assuming there's no strong desire to do this, closing it until such time

Fair enough; can concur - evidently if the current organisation works for that long then it doesn't need changing. Not clear if anyone outside of the BBC uses this data.
