### ISSUE TITLE
Not getting expected brand and model on hitting below URL

### ISSUE THREAD

**Issue by swarnv01** [bbc/matterhorn#8]
On hitting below url we are getting Cannot Get 
https://connected-tv-service-matterhorn.api.bbc.co.uk/identify/ua/user-agent/json

User-agent source : https://connected-tv.files.bbci.co.uk/device-identification-data/data.json

**Comment by AlexChesters** [comment]
@swarnv01 I'm getting the following, is this not expected?
```
{
  "brand":null,
  "model":null
}
```

**Comment by swarnv01** [comment]
I gues to test this we have to encode UA "https://connected-tv-service-matterhorn.test.api.bbc.co.uk/identify/ua/Mozilla%2F5.0%2520(Macintosh%3B%2520Intel%2520Mac%2520OS%2520X%252010_10_5)%2520AppleWebKit%2F537.36%2520(KHTML%2C%2520like%2520Gecko)%2520Chrome%2F46.0.2490.80%2520Safari%2F537.36/json"
